name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI_BAR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    container:
      image: maven:latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}

      # Download Maven Artifact
      - name: Download Maven Artifact
        run: mvn -q dependency:get -Dartifact=com.example:mybar:latest:jar -DremoteRepositories=https://mvn.pkg.github.com/testing

      - name: Output file path in container
        run: |
          echo "File has been downloaded to $HOME/.m2/repository/com/example/mybar/latest/mybar-latest.jar"
      
      # Add deployment steps using the downloaded artifact
