name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI_BAR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      # Download Maven Artifact using PowerShell script
      - name: Download Maven Artifact
        run: powershell.exe -File path/to/downloadArtifact.ps1
      - name: Output file path in container
        run: |
            echo "File has been downloaded to $HOME/.m2/repository/com/example/mybar/latest/mybar-latest.jar"
      
      # Add deployment steps using the downloaded artifact
