name: CI_BAR
on:
  push:
    branches:
      - features/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install BAR to local Maven repository
        run: mvn install:install-file -Dfile="C:\Users\Admin\Projects\actions-runner\_work\testing\testing\mybar-0.1.4.bar" -DgroupId=com.example -DartifactId=mybar -Dversion=0.1.4 -Dpackaging=bar
      - name: Build and Deploy
        run: |
          mvn clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.BAR_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/*.bar
